# Generated by Django 4.2.4 on 2023-08-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordado',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
